name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Execute shell script
      run: ./ascii.sh