name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: List the files
      run: ls -lrta

    - name: Execute shell script
      run: |
        chmod +x ascii.sh
        ./ascii.sh