name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: List the files
      run: ls -lrta

    - name: Make script executable
      run: chmod +x ascii-script.sh

    - name: Execute shell script
      run: ./ascii-script.sh
      shell: bash